### PR TITLE
Plugins

### PR DESCRIPTION
**Pull request by xpunch**
update plugins release script

### CODE REVIEW

**Comment by asim** [comment]
Do you want a separate windows script? Or maybe to detect OS? Because I don't use windows.

**Comment by asim** [comment]
When you get a chance can you also look at cmd/protoc-gen-micro, I think it might suffer from similar issues and maybe examples repo too

**Comment by xpunch** [comment]
Ok,I'll handle those modules too.

**Comment by asim** [comment]
Thank you

**Comment by asim** [comment]
If you learn of how to make vanity URLs and sub modules work let me know. I fought that quite hard and lost

**Comment by xpunch** [comment]
The offical document about [Multi Module Repositories](https://github.com/golang/go/wiki/Modules#what-are-multi-module-repositories) didn't mention vanity URLs for submodules too, seems there is no very good way to do so.

**Pull request merged**
